# Generated by Django 5.2.8 on 2025-12-01 05:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_options_task_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Команданын аты')),
                ('description', models.TextField(blank=True, verbose_name='Сүрөттөмөсү')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Түзүлгөн күнү')),
                ('members', models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Мүчөлөрү')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Командалар',
                'ordering': ['name'],
            },
        ),
    ]
